"""ORM models.

Importing this package registers every mapper on :class:`~src.models.base.Base`,
which is what Alembic autogenerate and the test fixtures rely on. Add new model
modules to the imports below or they will be silently missing from migrations.
"""

from src.models.base import (
    Base,
    SoftDeleteMixin,
    TenantScoped,
    TimestampMixin,
    new_id,
)
from src.models.conversation import (
    Citation,
    Conversation,
    FeedbackRating,
    Message,
    MessageFeedback,
    MessageRole,
    MessageStatus,
)
from src.models.document import (
    EMBEDDING_DIM,
    Chunk,
    ChunkKind,
    Document,
    DocumentStatus,
    DocumentVersion,
    IngestionJob,
    SourceType,
)
from src.models.evaluation import (
    DriftSnapshot,
    EvalCaseResult,
    EvalRun,
    EvalRunStatus,
    EvalSetName,
    Experiment,
    ExperimentStatus,
    JudgeCalibration,
    PromptRecord,
)
from src.models.telemetry import (
    AuditLog,
    GuardrailDecision,
    GuardrailEvent,
    GuardrailKind,
    GuardrailStage,
    RetrievalLog,
    TenantBudgetCounter,
    UsageRecord,
    WebhookDelivery,
    WebhookEndpoint,
)
from src.models.tenant import (
    ApiKey,
    ApiKeyScope,
    ChunkingStrategy,
    RetrievalStrategy,
    Tenant,
    TenantPlan,
    User,
)

__all__ = [
    "EMBEDDING_DIM",
    "ApiKey",
    "ApiKeyScope",
    "AuditLog",
    "Base",
    "Chunk",
    "ChunkKind",
    "ChunkingStrategy",
    "Citation",
    "Conversation",
    "Document",
    "DocumentStatus",
    "DocumentVersion",
    "DriftSnapshot",
    "EvalCaseResult",
    "EvalRun",
    "EvalRunStatus",
    "EvalSetName",
    "Experiment",
    "ExperimentStatus",
    "FeedbackRating",
    "GuardrailDecision",
    "GuardrailEvent",
    "GuardrailKind",
    "GuardrailStage",
    "IngestionJob",
    "JudgeCalibration",
    "Message",
    "MessageFeedback",
    "MessageRole",
    "MessageStatus",
    "PromptRecord",
    "RetrievalLog",
    "RetrievalStrategy",
    "SoftDeleteMixin",
    "SourceType",
    "Tenant",
    "TenantBudgetCounter",
    "TenantPlan",
    "TenantScoped",
    "TimestampMixin",
    "UsageRecord",
    "User",
    "WebhookDelivery",
    "WebhookEndpoint",
    "new_id",
]
