"""Initial schema.

Written as explicit DDL rather than generated ``op.create_table`` calls, for two
reasons. It is frozen: the statements below are what will run, and they cannot
drift when a model changes later. And it can express what Alembic cannot — the
HNSW index carries its build parameters (``m=16``, ``ef_construction=200``),
which autogenerate would silently drop and then propose to recreate on every
subsequent revision.

The extensions come first. ``vector`` is required by the chunks table, and
creating it inside the migration rather than relying on the container's init
script means a migration against a managed Postgres works too.

Revision ID: 0001_initial
Revises:
Created: 2026-09-04
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EXTENSIONS = (
    "CREATE EXTENSION IF NOT EXISTS vector",
    "CREATE EXTENSION IF NOT EXISTS pg_trgm",
)

#: Compiled for PostgreSQL 16 from the models in src/models. Ordered so foreign
#: keys resolve: a table always appears after everything it references.
STATEMENTS: tuple[str, ...] = (
    """CREATE TABLE conversations (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(64),
	title VARCHAR(300) NOT NULL,
	is_pinned BOOLEAN NOT NULL,
	active_leaf_message_id VARCHAR(64),
	running_summary TEXT,
	entity_memory JSONB NOT NULL,
	summarised_through_ordinal INTEGER NOT NULL,
	model VARCHAR(100),
	prompt_version VARCHAR(50),
	conversation_metadata JSONB NOT NULL,
	total_tokens INTEGER NOT NULL,
	total_cost_usd NUMERIC(12, 6) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_conversations PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_conversations_created_at ON conversations (created_at)""",
    """CREATE INDEX ix_conversations_deleted_at ON conversations (deleted_at)""",
    """CREATE INDEX ix_conversations_tenant_id ON conversations (tenant_id)""",
    """CREATE INDEX ix_conversations_tenant_id_updated_at ON conversations (tenant_id, updated_at)""",
    """CREATE INDEX ix_conversations_tenant_id_user_id ON conversations (tenant_id, user_id)""",
    """CREATE TABLE documents (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	title VARCHAR(500) NOT NULL,
	filename VARCHAR(500),
	mime_type VARCHAR(150),
	source_type VARCHAR(20) NOT NULL,
	source_uri TEXT,
	status VARCHAR(20) NOT NULL,
	error_message TEXT,
	current_version INTEGER NOT NULL,
	content_hash VARCHAR(64),
	byte_size BIGINT,
	page_count INTEGER,
	language VARCHAR(16),
	tags JSONB NOT NULL,
	doc_metadata JSONB NOT NULL,
	effective_date TIMESTAMP WITH TIME ZONE,
	uploaded_by_user_id VARCHAR(64),
	indexed_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_documents PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_documents_created_at ON documents (created_at)""",
    """CREATE INDEX ix_documents_deleted_at ON documents (deleted_at)""",
    """CREATE INDEX ix_documents_effective_date ON documents (effective_date)""",
    """CREATE INDEX ix_documents_status ON documents (status)""",
    """CREATE INDEX ix_documents_tenant_id ON documents (tenant_id)""",
    """CREATE INDEX ix_documents_tenant_id_content_hash ON documents (tenant_id, content_hash)""",
    """CREATE INDEX ix_documents_tenant_id_status ON documents (tenant_id, status)""",
    """CREATE TABLE eval_runs (
	id VARCHAR(64) NOT NULL,
	set_name VARCHAR(20) NOT NULL,
	set_version VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL,
	model VARCHAR(100) NOT NULL,
	prompt_version VARCHAR(50),
	retrieval_strategies JSONB NOT NULL,
	git_sha VARCHAR(40),
	git_branch VARCHAR(200),
	pr_number INTEGER,
	triggered_by VARCHAR(40) NOT NULL,
	case_count INTEGER NOT NULL,
	passed_count INTEGER NOT NULL,
	failed_count INTEGER NOT NULL,
	metrics JSONB NOT NULL,
	baseline_metrics JSONB,
	metric_deltas JSONB,
	gate_passed BOOLEAN,
	gate_failures JSONB NOT NULL,
	total_cost_usd NUMERIC(12, 6) NOT NULL,
	duration_seconds FLOAT,
	report_url TEXT,
	langfuse_url TEXT,
	finished_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_eval_runs PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_eval_runs_created_at ON eval_runs (created_at)""",
    """CREATE INDEX ix_eval_runs_git_sha ON eval_runs (git_sha)""",
    """CREATE INDEX ix_eval_runs_pr_number ON eval_runs (pr_number)""",
    """CREATE INDEX ix_eval_runs_set_name_created_at ON eval_runs (set_name, created_at)""",
    """CREATE TABLE judge_calibrations (
	id VARCHAR(64) NOT NULL,
	judge_model VARCHAR(100) NOT NULL,
	calibration_set_version VARCHAR(20) NOT NULL,
	sample_size INTEGER NOT NULL,
	expected_calibration_error FLOAT NOT NULL,
	cohens_kappa FLOAT,
	pearson_r FLOAT,
	mean_absolute_error FLOAT,
	slope FLOAT NOT NULL,
	intercept FLOAT NOT NULL,
	weight FLOAT NOT NULL,
	reliability_bins JSONB NOT NULL,
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL,
	is_active BOOLEAN NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_judge_calibrations PRIMARY KEY (id),
	CONSTRAINT uq_judge_calibrations_model_time UNIQUE (judge_model, computed_at)
)""",
    """CREATE INDEX ix_judge_calibrations_created_at ON judge_calibrations (created_at)""",
    """CREATE INDEX ix_judge_calibrations_is_active ON judge_calibrations (is_active)""",
    """CREATE INDEX ix_judge_calibrations_judge_model ON judge_calibrations (judge_model)""",
    """CREATE TABLE prompt_records (
	id VARCHAR(64) NOT NULL,
	name VARCHAR(100) NOT NULL,
	version VARCHAR(20) NOT NULL,
	content_hash VARCHAR(64) NOT NULL,
	template TEXT NOT NULL,
	variables JSONB NOT NULL,
	author VARCHAR(200),
	changelog TEXT,
	is_active BOOLEAN NOT NULL,
	promoted_at TIMESTAMP WITH TIME ZONE,
	promoted_by VARCHAR(200),
	promoted_from_run_id VARCHAR(64),
	langfuse_prompt_id VARCHAR(120),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_prompt_records PRIMARY KEY (id),
	CONSTRAINT uq_prompt_records_name_version UNIQUE (name, version)
)""",
    """CREATE INDEX ix_prompt_records_content_hash ON prompt_records (content_hash)""",
    """CREATE INDEX ix_prompt_records_created_at ON prompt_records (created_at)""",
    """CREATE INDEX ix_prompt_records_name_is_active ON prompt_records (name, is_active)""",
    """CREATE TABLE experiments (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	name VARCHAR(200) NOT NULL,
	hypothesis TEXT,
	status VARCHAR(20) NOT NULL,
	control JSONB NOT NULL,
	variant JSONB NOT NULL,
	variant_traffic_pct FLOAT NOT NULL,
	is_shadow BOOLEAN NOT NULL,
	primary_metric VARCHAR(60) NOT NULL,
	minimum_sample_size INTEGER NOT NULL,
	auto_promote BOOLEAN NOT NULL,
	auto_rollback_threshold FLOAT NOT NULL,
	control_stats JSONB NOT NULL,
	variant_stats JSONB NOT NULL,
	p_value FLOAT,
	decided_at TIMESTAMP WITH TIME ZONE,
	decision_note TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_experiments PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_experiments_created_at ON experiments (created_at)""",
    """CREATE INDEX ix_experiments_tenant_id ON experiments (tenant_id)""",
    """CREATE INDEX ix_experiments_tenant_id_status ON experiments (tenant_id, status)""",
    """CREATE TABLE drift_snapshots (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	snapshot_date TIMESTAMP WITH TIME ZONE NOT NULL,
	metric VARCHAR(60) NOT NULL,
	histogram JSONB NOT NULL,
	sample_size INTEGER NOT NULL,
	psi FLOAT,
	kl_divergence FLOAT,
	alerted BOOLEAN NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_drift_snapshots PRIMARY KEY (id),
	CONSTRAINT uq_drift_snapshots_tenant_date_metric UNIQUE (tenant_id, snapshot_date, metric)
)""",
    """CREATE INDEX ix_drift_snapshots_created_at ON drift_snapshots (created_at)""",
    """CREATE INDEX ix_drift_snapshots_tenant_id ON drift_snapshots (tenant_id)""",
    """CREATE TABLE guardrail_events (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	message_id VARCHAR(64),
	conversation_id VARCHAR(64),
	user_id VARCHAR(64),
	trace_id VARCHAR(64),
	stage VARCHAR(10) NOT NULL,
	kind VARCHAR(30) NOT NULL,
	decision VARCHAR(10) NOT NULL,
	detector VARCHAR(60),
	score FLOAT,
	threshold FLOAT,
	reason TEXT,
	evidence JSONB NOT NULL,
	latency_ms INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_guardrail_events PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_guardrail_events_created_at ON guardrail_events (created_at)""",
    """CREATE INDEX ix_guardrail_events_decision ON guardrail_events (decision)""",
    """CREATE INDEX ix_guardrail_events_message_id ON guardrail_events (message_id)""",
    """CREATE INDEX ix_guardrail_events_tenant_id ON guardrail_events (tenant_id)""",
    """CREATE INDEX ix_guardrail_events_tenant_id_kind_created_at ON guardrail_events (tenant_id, kind, created_at)""",
    """CREATE INDEX ix_guardrail_events_trace_id ON guardrail_events (trace_id)""",
    """CREATE TABLE retrieval_logs (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	message_id VARCHAR(64),
	trace_id VARCHAR(64),
	query TEXT NOT NULL,
	rewritten_queries JSONB NOT NULL,
	strategy VARCHAR(40) NOT NULL,
	top_k INTEGER NOT NULL,
	expanded BOOLEAN NOT NULL,
	result_count INTEGER NOT NULL,
	chunk_ids JSONB NOT NULL,
	scores JSONB NOT NULL,
	rerank_scores JSONB NOT NULL,
	top_score FLOAT,
	mean_score FLOAT,
	crag_verdict VARCHAR(20),
	web_fallback_used BOOLEAN NOT NULL,
	dense_latency_ms INTEGER,
	sparse_latency_ms INTEGER,
	rerank_latency_ms INTEGER,
	total_latency_ms INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_retrieval_logs PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_retrieval_logs_created_at ON retrieval_logs (created_at)""",
    """CREATE INDEX ix_retrieval_logs_message_id ON retrieval_logs (message_id)""",
    """CREATE INDEX ix_retrieval_logs_strategy ON retrieval_logs (strategy)""",
    """CREATE INDEX ix_retrieval_logs_tenant_id ON retrieval_logs (tenant_id)""",
    """CREATE INDEX ix_retrieval_logs_tenant_id_created_at ON retrieval_logs (tenant_id, created_at)""",
    """CREATE INDEX ix_retrieval_logs_top_score ON retrieval_logs (top_score)""",
    """CREATE INDEX ix_retrieval_logs_trace_id ON retrieval_logs (trace_id)""",
    """CREATE TABLE usage_records (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(64),
	conversation_id VARCHAR(64),
	message_id VARCHAR(64),
	trace_id VARCHAR(64),
	usage_date DATE NOT NULL,
	provider VARCHAR(40) NOT NULL,
	model VARCHAR(100) NOT NULL,
	operation VARCHAR(40) NOT NULL,
	node VARCHAR(60),
	prompt_tokens INTEGER NOT NULL,
	completion_tokens INTEGER NOT NULL,
	cached_tokens INTEGER NOT NULL,
	cost_usd NUMERIC(12, 6) NOT NULL,
	latency_ms INTEGER,
	was_fallback BOOLEAN NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_usage_records PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_usage_records_created_at ON usage_records (created_at)""",
    """CREATE INDEX ix_usage_records_message_id ON usage_records (message_id)""",
    """CREATE INDEX ix_usage_records_tenant_id ON usage_records (tenant_id)""",
    """CREATE INDEX ix_usage_records_tenant_id_model ON usage_records (tenant_id, model)""",
    """CREATE INDEX ix_usage_records_tenant_id_usage_date ON usage_records (tenant_id, usage_date)""",
    """CREATE INDEX ix_usage_records_usage_date ON usage_records (usage_date)""",
    """CREATE TABLE tenant_budget_counters (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	usage_date DATE NOT NULL,
	tokens_used BIGINT NOT NULL,
	cost_usd NUMERIC(12, 6) NOT NULL,
	requests INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_tenant_budget_counters PRIMARY KEY (id),
	CONSTRAINT uq_tenant_budget_counters_tenant_date UNIQUE (tenant_id, usage_date)
)""",
    """CREATE INDEX ix_tenant_budget_counters_created_at ON tenant_budget_counters (created_at)""",
    """CREATE INDEX ix_tenant_budget_counters_tenant_id ON tenant_budget_counters (tenant_id)""",
    """CREATE TABLE audit_logs (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	actor_user_id VARCHAR(64),
	actor_api_key_id VARCHAR(64),
	actor_ip VARCHAR(45),
	action VARCHAR(80) NOT NULL,
	resource_type VARCHAR(60),
	resource_id VARCHAR(64),
	before JSONB,
	after JSONB,
	success BOOLEAN NOT NULL,
	trace_id VARCHAR(64),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_audit_logs PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_audit_logs_actor_user_id ON audit_logs (actor_user_id)""",
    """CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at)""",
    """CREATE INDEX ix_audit_logs_tenant_id ON audit_logs (tenant_id)""",
    """CREATE INDEX ix_audit_logs_tenant_id_created_at ON audit_logs (tenant_id, created_at)""",
    """CREATE TABLE webhook_endpoints (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	url TEXT NOT NULL,
	events JSONB NOT NULL,
	secret_hash VARCHAR(64) NOT NULL,
	is_active BOOLEAN NOT NULL,
	description VARCHAR(300),
	consecutive_failures INTEGER NOT NULL,
	disabled_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_webhook_endpoints PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_webhook_endpoints_created_at ON webhook_endpoints (created_at)""",
    """CREATE INDEX ix_webhook_endpoints_tenant_id ON webhook_endpoints (tenant_id)""",
    """CREATE TABLE webhook_deliveries (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	endpoint_id VARCHAR(64) NOT NULL,
	event VARCHAR(60) NOT NULL,
	payload JSONB NOT NULL,
	attempt INTEGER NOT NULL,
	status_code INTEGER,
	error TEXT,
	delivered_at TIMESTAMP WITH TIME ZONE,
	next_retry_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_webhook_deliveries PRIMARY KEY (id)
)""",
    """CREATE INDEX ix_webhook_deliveries_created_at ON webhook_deliveries (created_at)""",
    """CREATE INDEX ix_webhook_deliveries_endpoint_created ON webhook_deliveries (endpoint_id, created_at)""",
    """CREATE INDEX ix_webhook_deliveries_next_retry_at ON webhook_deliveries (next_retry_at)""",
    """CREATE INDEX ix_webhook_deliveries_tenant_id ON webhook_deliveries (tenant_id)""",
    """CREATE TABLE tenants (
	id VARCHAR(64) NOT NULL,
	clerk_org_id VARCHAR(128),
	name VARCHAR(200) NOT NULL,
	slug VARCHAR(100) NOT NULL,
	plan VARCHAR(20) NOT NULL,
	embedding_model VARCHAR(200) NOT NULL,
	chunking_strategy VARCHAR(32) NOT NULL,
	enabled_strategies JSONB NOT NULL,
	contextual_retrieval_enabled BOOLEAN NOT NULL,
	graph_extraction_enabled BOOLEAN NOT NULL,
	custom_instructions TEXT,
	response_template TEXT,
	guardrail_config JSONB NOT NULL,
	model_policy JSONB NOT NULL,
	daily_token_budget BIGINT NOT NULL,
	monthly_cost_cap_usd NUMERIC(12, 4),
	data_region VARCHAR(32) NOT NULL,
	retention_days INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_tenants PRIMARY KEY (id)
)""",
    """CREATE UNIQUE INDEX ix_tenants_clerk_org_id ON tenants (clerk_org_id)""",
    """CREATE INDEX ix_tenants_created_at ON tenants (created_at)""",
    """CREATE INDEX ix_tenants_deleted_at ON tenants (deleted_at)""",
    """CREATE UNIQUE INDEX ix_tenants_slug ON tenants (slug)""",
    """CREATE TABLE messages (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	conversation_id VARCHAR(64) NOT NULL,
	parent_message_id VARCHAR(64),
	role VARCHAR(20) NOT NULL,
	content TEXT NOT NULL,
	status VARCHAR(20) NOT NULL,
	model VARCHAR(100),
	provider VARCHAR(40),
	prompt_version VARCHAR(50),
	intent VARCHAR(40),
	strategies_used JSONB NOT NULL,
	node_trace JSONB NOT NULL,
	tool_calls JSONB NOT NULL,
	prompt_tokens INTEGER NOT NULL,
	completion_tokens INTEGER NOT NULL,
	cost_usd NUMERIC(12, 6) NOT NULL,
	ttft_ms INTEGER,
	ttlt_ms INTEGER,
	cache_hit VARCHAR(20),
	groundedness_score FLOAT,
	self_critique TEXT,
	guardrail_flags JSONB NOT NULL,
	trace_id VARCHAR(64),
	langfuse_trace_url TEXT,
	error_message TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_messages PRIMARY KEY (id),
	CONSTRAINT fk_messages_conversation_id_conversations FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
	CONSTRAINT fk_messages_parent_message_id_messages FOREIGN KEY(parent_message_id) REFERENCES messages (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_messages_conversation_id_created_at ON messages (conversation_id, created_at)""",
    """CREATE INDEX ix_messages_created_at ON messages (created_at)""",
    """CREATE INDEX ix_messages_parent_message_id ON messages (parent_message_id)""",
    """CREATE INDEX ix_messages_tenant_id ON messages (tenant_id)""",
    """CREATE INDEX ix_messages_tenant_id_role ON messages (tenant_id, role)""",
    """CREATE INDEX ix_messages_trace_id ON messages (trace_id)""",
    """CREATE TABLE document_versions (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	document_id VARCHAR(64) NOT NULL,
	version INTEGER NOT NULL,
	storage_key VARCHAR(500) NOT NULL,
	content_hash VARCHAR(64) NOT NULL,
	extracted_text TEXT,
	parser VARCHAR(64),
	parse_metadata JSONB NOT NULL,
	is_current BOOLEAN NOT NULL,
	created_by_user_id VARCHAR(64),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_document_versions PRIMARY KEY (id),
	CONSTRAINT uq_document_versions_document_id_version UNIQUE (document_id, version),
	CONSTRAINT fk_document_versions_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_document_versions_created_at ON document_versions (created_at)""",
    """CREATE INDEX ix_document_versions_document_id ON document_versions (document_id)""",
    """CREATE INDEX ix_document_versions_tenant_id ON document_versions (tenant_id)""",
    """CREATE TABLE ingestion_jobs (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	document_id VARCHAR(64) NOT NULL,
	celery_task_id VARCHAR(128),
	status VARCHAR(20) NOT NULL,
	stage VARCHAR(50),
	progress FLOAT NOT NULL,
	attempts INTEGER NOT NULL,
	max_attempts INTEGER NOT NULL,
	last_error TEXT,
	dead_lettered_at TIMESTAMP WITH TIME ZONE,
	started_at TIMESTAMP WITH TIME ZONE,
	finished_at TIMESTAMP WITH TIME ZONE,
	chunks_created INTEGER NOT NULL,
	embedding_tokens INTEGER NOT NULL,
	cost_usd FLOAT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_ingestion_jobs PRIMARY KEY (id),
	CONSTRAINT fk_ingestion_jobs_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_ingestion_jobs_celery_task_id ON ingestion_jobs (celery_task_id)""",
    """CREATE INDEX ix_ingestion_jobs_created_at ON ingestion_jobs (created_at)""",
    """CREATE INDEX ix_ingestion_jobs_document_id ON ingestion_jobs (document_id)""",
    """CREATE INDEX ix_ingestion_jobs_tenant_id ON ingestion_jobs (tenant_id)""",
    """CREATE INDEX ix_ingestion_jobs_tenant_id_created_at ON ingestion_jobs (tenant_id, created_at)""",
    """CREATE TABLE eval_case_results (
	id VARCHAR(64) NOT NULL,
	run_id VARCHAR(64) NOT NULL,
	case_id VARCHAR(80) NOT NULL,
	intent VARCHAR(40),
	difficulty VARCHAR(20),
	query TEXT NOT NULL,
	expected_answer TEXT,
	actual_answer TEXT,
	expected_sources JSONB NOT NULL,
	retrieved_sources JSONB NOT NULL,
	metrics JSONB NOT NULL,
	judge_scores JSONB NOT NULL,
	calibrated_score FLOAT,
	judges_disagreed BOOLEAN NOT NULL,
	human_label FLOAT,
	passed BOOLEAN NOT NULL,
	failure_mode VARCHAR(60),
	latency_ms INTEGER,
	cost_usd NUMERIC(12, 6) NOT NULL,
	trace_id VARCHAR(64),
	langfuse_url TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_eval_case_results PRIMARY KEY (id),
	CONSTRAINT uq_eval_case_results_run_id_case_id UNIQUE (run_id, case_id),
	CONSTRAINT fk_eval_case_results_run_id_eval_runs FOREIGN KEY(run_id) REFERENCES eval_runs (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_eval_case_results_created_at ON eval_case_results (created_at)""",
    """CREATE INDEX ix_eval_case_results_intent ON eval_case_results (intent)""",
    """CREATE INDEX ix_eval_case_results_judges_disagreed ON eval_case_results (judges_disagreed)""",
    """CREATE INDEX ix_eval_case_results_run_id_passed ON eval_case_results (run_id, passed)""",
    """CREATE TABLE users (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	clerk_user_id VARCHAR(128) NOT NULL,
	email VARCHAR(320) NOT NULL,
	display_name VARCHAR(200),
	role VARCHAR(32) NOT NULL,
	last_seen_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT uq_users_tenant_id_clerk_user_id UNIQUE (tenant_id, clerk_user_id),
	CONSTRAINT fk_users_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_users_created_at ON users (created_at)""",
    """CREATE INDEX ix_users_deleted_at ON users (deleted_at)""",
    """CREATE INDEX ix_users_tenant_id ON users (tenant_id)""",
    """CREATE INDEX ix_users_tenant_id_email ON users (tenant_id, email)""",
    """CREATE TABLE api_keys (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	name VARCHAR(200) NOT NULL,
	key_hash VARCHAR(64) NOT NULL,
	prefix VARCHAR(16) NOT NULL,
	scopes JSONB NOT NULL,
	created_by_user_id VARCHAR(64),
	last_used_at TIMESTAMP WITH TIME ZONE,
	expires_at TIMESTAMP WITH TIME ZONE,
	revoked_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_api_keys PRIMARY KEY (id),
	CONSTRAINT fk_api_keys_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_api_keys_created_at ON api_keys (created_at)""",
    """CREATE UNIQUE INDEX ix_api_keys_key_hash ON api_keys (key_hash)""",
    """CREATE INDEX ix_api_keys_tenant_id ON api_keys (tenant_id)""",
    """CREATE TABLE message_feedback (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	message_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(64),
	rating VARCHAR(10) NOT NULL,
	comment TEXT,
	failure_mode VARCHAR(60),
	triaged_by_user_id VARCHAR(64),
	triaged_at TIMESTAMP WITH TIME ZONE,
	promoted_to_regression_set BOOLEAN NOT NULL,
	regression_case_id VARCHAR(64),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_message_feedback PRIMARY KEY (id),
	CONSTRAINT fk_message_feedback_message_id_messages FOREIGN KEY(message_id) REFERENCES messages (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_message_feedback_created_at ON message_feedback (created_at)""",
    """CREATE INDEX ix_message_feedback_promoted ON message_feedback (promoted_to_regression_set)""",
    """CREATE INDEX ix_message_feedback_promoted_to_regression_set ON message_feedback (promoted_to_regression_set)""",
    """CREATE INDEX ix_message_feedback_tenant_id ON message_feedback (tenant_id)""",
    """CREATE INDEX ix_message_feedback_tenant_id_rating ON message_feedback (tenant_id, rating)""",
    """CREATE TABLE chunks (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	document_id VARCHAR(64) NOT NULL,
	document_version_id VARCHAR(64),
	ordinal INTEGER NOT NULL,
	kind VARCHAR(20) NOT NULL,
	content TEXT NOT NULL,
	embedded_text TEXT,
	context_preamble TEXT,
	embedding VECTOR(1024),
	embedding_model VARCHAR(200),
	token_count INTEGER,
	char_start INTEGER,
	char_end INTEGER,
	page_number INTEGER,
	section_path VARCHAR(1000),
	bbox JSONB,
	minhash_signature VARCHAR(64),
	is_stale BOOLEAN NOT NULL,
	chunk_metadata JSONB NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_chunks PRIMARY KEY (id),
	CONSTRAINT fk_chunks_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE,
	CONSTRAINT fk_chunks_document_version_id_document_versions FOREIGN KEY(document_version_id) REFERENCES document_versions (id) ON DELETE CASCADE
)""",
    """CREATE INDEX ix_chunks_created_at ON chunks (created_at)""",
    """CREATE INDEX ix_chunks_embedding_hnsw ON chunks USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 200)""",
    """CREATE INDEX ix_chunks_minhash_signature ON chunks (minhash_signature)""",
    """CREATE INDEX ix_chunks_tenant_id ON chunks (tenant_id)""",
    """CREATE INDEX ix_chunks_tenant_id_document_id ON chunks (tenant_id, document_id)""",
    """CREATE INDEX ix_chunks_tenant_id_is_stale ON chunks (tenant_id, is_stale)""",
    """CREATE TABLE citations (
	id VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	message_id VARCHAR(64) NOT NULL,
	chunk_id VARCHAR(64),
	document_id VARCHAR(64),
	marker INTEGER NOT NULL,
	claim TEXT,
	quote TEXT,
	retrieval_score FLOAT,
	rerank_score FLOAT,
	entailment_score FLOAT,
	verified BOOLEAN NOT NULL,
	dropped_reason VARCHAR(100),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_citations PRIMARY KEY (id),
	CONSTRAINT fk_citations_message_id_messages FOREIGN KEY(message_id) REFERENCES messages (id) ON DELETE CASCADE,
	CONSTRAINT fk_citations_chunk_id_chunks FOREIGN KEY(chunk_id) REFERENCES chunks (id) ON DELETE SET NULL
)""",
    """CREATE INDEX ix_citations_created_at ON citations (created_at)""",
    """CREATE INDEX ix_citations_document_id ON citations (document_id)""",
    """CREATE INDEX ix_citations_message_id_marker ON citations (message_id, marker)""",
    """CREATE INDEX ix_citations_tenant_id ON citations (tenant_id)""",
)

#: Reverse order, so a table is dropped before whatever it depends on.
DROP_STATEMENTS: tuple[str, ...] = (
    "DROP TABLE IF EXISTS citations CASCADE",
    "DROP TABLE IF EXISTS chunks CASCADE",
    "DROP TABLE IF EXISTS message_feedback CASCADE",
    "DROP TABLE IF EXISTS api_keys CASCADE",
    "DROP TABLE IF EXISTS users CASCADE",
    "DROP TABLE IF EXISTS eval_case_results CASCADE",
    "DROP TABLE IF EXISTS ingestion_jobs CASCADE",
    "DROP TABLE IF EXISTS document_versions CASCADE",
    "DROP TABLE IF EXISTS messages CASCADE",
    "DROP TABLE IF EXISTS tenants CASCADE",
    "DROP TABLE IF EXISTS webhook_deliveries CASCADE",
    "DROP TABLE IF EXISTS webhook_endpoints CASCADE",
    "DROP TABLE IF EXISTS audit_logs CASCADE",
    "DROP TABLE IF EXISTS tenant_budget_counters CASCADE",
    "DROP TABLE IF EXISTS usage_records CASCADE",
    "DROP TABLE IF EXISTS retrieval_logs CASCADE",
    "DROP TABLE IF EXISTS guardrail_events CASCADE",
    "DROP TABLE IF EXISTS drift_snapshots CASCADE",
    "DROP TABLE IF EXISTS experiments CASCADE",
    "DROP TABLE IF EXISTS prompt_records CASCADE",
    "DROP TABLE IF EXISTS judge_calibrations CASCADE",
    "DROP TABLE IF EXISTS eval_runs CASCADE",
    "DROP TABLE IF EXISTS documents CASCADE",
    "DROP TABLE IF EXISTS conversations CASCADE",
)


def upgrade() -> None:
    """Create the extensions, tables and indexes."""
    for statement in EXTENSIONS:
        op.execute(statement)
    for statement in STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    """Drop every table.

    The extensions are deliberately left in place: another schema in the same
    database may be using pgvector, and dropping it from under them would be a
    far worse outcome than leaving an unused extension behind.
    """
    for statement in DROP_STATEMENTS:
        op.execute(statement)
